baseURL: https://akshatkacheria.netlify.app
languageCode: en-us
title: Akshat
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Click Here
    subtitle: |-
      Take a look at my portfolio of projects.
    title: Akshat Kacheria
  blog: {}
  contact:
    address:
      - city: London, NW1 4SA
        country: United Kingdom
        street: Regents Park, Park Road
        title: London Business School
    email:
      - email: akacheria.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 077-6551 8136
        title: Phone
    buttonSend: "Send message"
    buttonClear: "Clear"
  custom_css: []
  custom_js: []
  description: Akshat Here
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Akshat Kacheria 2021
    enable: yes
    quicklinks:
      - alt: #
        text: Find my LinkedIn & GitHub Above
        url: #
    social:
      - icon: fa-github
        label: GitHub
        url: https://github.com/AkshatKacheria
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/akshatkacheria/
  image: ''
  name: Akshat Kacheria
  navigation:
    button1:
      - name: Get Started
        url: blogs
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
     # - name: Generic Blog
     #   url: blogs/ipsum
     # - name: Elements
     #   url: elements.html
    menu: Menu
    subtitle: ""
    title: Home Page
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpeg
        subtitle: My short story
        title: About Me
        url: blogs/akbio
      - image: brexit.png
        subtitle: Analysing the factors that affected the Brexit vote amongst the UK population
        title: Brexit Data Project
        url: blogs/brexit
      - image: pic03.png
        subtitle: Analysing youth behaviour and Risk using data and statistics
        title: Youth Behaviour Risk Project
        url: blogs/youthbehaviour
      - image: pic04.jpg
        subtitle: Research Project on Brain Interfacing to move and control a wheelchair
        title: Brain Controlled Wheelchair
        url: blogs/braincontrol
  #    - image: pic05.jpg
  #      subtitle: Ipsum Dolor Sit Amet
  #      title: Consequat
  #      url: blogs/ipsum
  #   - image: pic06.jpg
  #      subtitle: Feugiat Amet Tempus
  #      title: Etiam
  #      url: blogs/ipsum
  two:
    buttonText: Download PDF
    enable: yes
    subtitle: Scan here or click below for my professional resume
    title: Resume
    url: https://drive.google.com/file/d/1MvRS3NExFfZ3fuu8EzA7e4UhUaWHcJqV/view?usp=sharing
